### ISSUE TITLE
Any way to prevent notifications when iTerm2 stops to wait for GUI app?

### ISSUE THREAD

**Issue by phatblat** [fisherman/done#21] opened 2017-05-20 19:55 UTC
I have an `editw` function that opens a file in TextMate and waits (`mate -w`) for the file to be closed before allowing the terminal to continue. This is the only way to use a GUI editor for things like git commit messages or interactive rebase. The `editw` function falls back to using Vim for non-login shells and SSH connections. 

I get no notification when this function ends up launching Vim since it lives in the terminal, but when TextMate is invoked from the terminal, I always get a notification from done when it closes and the terminal continues.

<img width="329" alt="screen shot 2017-05-20 at 1 27 00 pm" src="https://cloud.githubusercontent.com/assets/28851/26278810/bab864f6-3d60-11e7-8926-34a6ce75ad1a.png">

Is there a way to change this behavior?

It seems like a list of commands to exclude (like [this example](http://dawehner.github.io/fish/shell/2015/11/19/notify-long-commands.html)) might be the simplest way to accomplish this. The list would need to be user-configurable. I can submit a PR to introduce excluded commands unless someone knows of a better approach.

**Comment by aristidesfl** [comment] 2017-05-20 20:31
This has never happened to me since iTerm gets focus after the editor window is closed. I use Sublime Text, but also just tried to reproduce with Textmate without success.

Which version of iTerm, Textmate, macOS are you using?
Have you tried `fisher update`?

**Comment by aristidesfl** [comment] 2017-05-20 20:56
@phatblat do you get notification on the screen or only in notification center sidebar?

**Comment by phatblat** [comment] 2017-05-20 21:06
- iTerm
- TextMate 2.0-rc.7

**Comment by phatblat** [comment] 2017-05-20 21:12
I use iTerm2's Hotkey Window profile almost exclusively and didn't think about how that is a factor. When the focus moves from iTerm2 to TextMate, the iTerm2 window disappears. So, when I'm done editing and the terminal continues, it is hidden and does not have the focus.

Testing with a normal iTerm2 window, I get no notifications at all. With the Hotkey Window, I get a notification only in the Notification Center sidebar - no on-screen banner. There have been a couple times I've gotten an on-screen banner, but I don't recall exactly what the situation was. I could be remembering time where the wait flag wasn't set correctly so the shell command finished immediately after launching TextMate.

**Comment by aristidesfl** [comment] 2017-05-21 18:13
It seems that even with normal iTerm window mode, the detection is not working because when the prompt function is executed lsappinfo still reports sublime/textmate as the frontmost window. However, by the time terminal-notifier is executed, lsappinfo reports iTerm as the frontmost window, so the notification is only displayed in the sidebar. 

Seems to be a matter of milliseconds..

**Comment by aristidesfl** [comment] 2017-05-21 18:46
@phatblat I'm experimenting with the iTerm hotkey, but the focus still returns to iTerm when its window is evoked with the hotkey. Anything else special?

**Comment by phatblat** [comment] 2017-05-21 19:49
Under Preferences > Keys

![screen shot 2017-05-21 at 1 48 10 pm](https://cloud.githubusercontent.com/assets/28851/26286871/2b9b8a1a-3e2c-11e7-9ea5-6ff0493279da.png)

The last checkbox makes the iTerm Hotkey Window disappear when it loses focus.

**Comment by aristidesfl** [comment] 2017-06-05 15:53
@phatblat do you use editw in any other situation besides git, or know any other utilities which open a GUI and wait before continuing? I'm considering disabling done for git and other version control commands.

Also its not clear on to detect editw usage, if you are typing git commit in the terminal.

**Comment by aristidesfl** [comment] 2017-06-05 16:37
Also it would probably not work if you have some alias for git commands.. :/

**Comment by aristidesfl** [comment] 2017-06-17 22:24
@phatblat I assume you have editw set as your git editor, right?

**Comment by aristidesfl** [comment] 2017-06-18 17:28
@phatblat this was fixed in https://github.com/fisherman/done/releases/tag/1.4.0 . Only git is excluded by default, but you can configure it with `$__done_exclude`. Let me know if you find any other commands which should be excluded by default, or removed from the exclusion.

**Closed by aristidesfl** 2017-06-18 17:28 UTC

**Comment by phatblat** [comment] 2017-06-18 19:04
Awesome! I'll try it out, thanks!
